/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingListingIdRouteImport } from './routes/listing/$listingId'
import { Route as AuctionAuctionIdRouteImport } from './routes/auction/$auctionId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingListingIdRoute = ListingListingIdRouteImport.update({
  id: '/listing/$listingId',
  path: '/listing/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionAuctionIdRoute = AuctionAuctionIdRouteImport.update({
  id: '/auction/$auctionId',
  path: '/auction/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/collections': typeof CollectionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auction/$auctionId': typeof AuctionAuctionIdRoute
  '/listing/$listingId': typeof ListingListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/auth'
    | '/browse'
    | '/collections'
    | '/admin'
    | '/profile'
    | '/auction/$auctionId'
    | '/listing/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/auth'
    | '/browse'
    | '/collections'
    | '/admin'
    | '/profile'
    | '/auction/$auctionId'
    | '/listing/$listingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auctions'
    | '/auth'
    | '/browse'
    | '/collections'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/auction/$auctionId'
    | '/listing/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CollectionsRoute: typeof CollectionsRoute
  AuctionAuctionIdRoute: typeof AuctionAuctionIdRoute
  ListingListingIdRoute: typeof ListingListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$listingId': {
      id: '/listing/$listingId'
      path: '/listing/$listingId'
      fullPath: '/listing/$listingId'
      preLoaderRoute: typeof ListingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$auctionId': {
      id: '/auction/$auctionId'
      path: '/auction/$auctionId'
      fullPath: '/auction/$auctionId'
      preLoaderRoute: typeof AuctionAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CollectionsRoute: CollectionsRoute,
  AuctionAuctionIdRoute: AuctionAuctionIdRoute,
  ListingListingIdRoute: ListingListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
